project:
  type: website
  output-dir: docs
  

website:
  title: "IsaacTechBlog"
  site-url: https://isaac-flath.github.io/TechBlog/
  description: "Blog for machine learning, programming, computer science and other data science related topics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/isaac-flath
      - icon: twitter
        href: https://twitter.com/isaac_flath
      - icon: mastodon
        href: https://sigmoid.social/web/@isaac_flath
format:
  html:
    theme: cosmo
    css: styles.css



