project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  title: "Isaac Flath"
  favicon: favicon/favicon-32x32.png
  open-graph:
    locale: en_US
  twitter-card: true
  site-url: https://isaac-flath.tech/
  description: "Blog for machine learning, programming, computer science and other data science related topics"
  navbar:
    right:
      - text: "About Me"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "TIL"
        file: til.qmd
      - icon: rss
        href: index.xml
  page-footer: 
    left: "Isaac Flath" 
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://linkedin.com/in/isaacflath/
      - icon: github
        text: Github
        href: https://github.com/isaac-flath
      - icon: twitter
        text: Twitter
        href: https://twitter.com/isaac_flath
      - icon: mastadon
        text: Mastadon
        href: https://sigmoid.social/web/@isaac_flath
format:
  html:
    theme: cosmo
    css: styles.css


